<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
	<ApplicationIcon>Assets\OpenXenium_CPLD_Flasher.ico</ApplicationIcon>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <AssemblyName>OpenXenium CPLD Flasher</AssemblyName>
    <RootNamespace>OpenXeniumCPLDFlasher</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Tools\**\*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
